

SELECT PRICE_SENSITIVITY, COUNT(*) TOTAL_ITEMS
FROM 
(
	SELECT A.NAME,RESTAURANT_ID, PRICE,
	CASE 
    WHEN PRICE>=0 AND PRICE<=5 THEN 'Low Value'
    WHEN PRICE>5 AND PRICE<=10 THEN 'MID VALUE'
    WHEN PRICE>10 THEN 'High Value' ELSE 'Unconditioned' END AS PRICE_SENSITIVITY 
	 FROM MenuItems A 
) B 
GROUP BY 1;


SELECT * FROM 
(
	SELECT A.NAME,RESTAURANT_ID,PRICE,
	CASE 
    WHEN PRICE BETWEEN 1 AND 5 THEN 'Low Value'
    WHEN PRICE BETWEEN 6 AND 10 THEN 'MID VALUE'
    WHEN PRICE>10 THEN 'High Value' ELSE 'Unconditioned' END AS PRICE_SENSITIVITY 
	 FROM MenuItems A 
) B 
WHERE PRICE_SENSITIVITY = 'Unconditioned'