#CONCAT
SELECT CONCAT(CITY_NAME,", Bangladesh") CITY_NAME
 FROM CITY;


#UPPER, LOWER 
SELECT UPPER(CITY_NAME) UPPER_NAME, LOWER(CITY_NAME) LOWER_NAME
 FROM CITY;
 
 #LENGTH
SELECT A.*, LENGTH(CITY_NAME) CITY_LENGHT
 FROM CITY A;
 
#SUBSTRING
SELECT A.*, SUBSTR(CITY_NAME,1,4) SUBSTR_CITY
 FROM CITY A;
 
#REPLACE
SELECT A.*, REPLACE(CITY_NAME,'ha',';)') REPLACED_VALUE
 FROM CITY A;
 
#LEFT , RIGHT
SELECT A.*, LEFT(CITY_NAME,4) LEFT_CITY, RIGHT(CITY_NAME,4) RIGHT_CITY
 FROM CITY A;