SELECT * FROM MENUITEMS
WHERE PRICE> ( SELECT AVG(PRICE) AS AVG_PRICE FROM MenuItems);

SELECT FIRST_ORDER_DATE, COUNT(USER_ID) NEW_USER
FROM 
(
	SELECT USER_ID, MIN(DATE(ORDER_DATE)) FIRST_ORDER_DATE
	 FROM ORDERS
	GROUP BY USER_ID
) AS FIRST_USER_DATE
GROUP BY FIRST_ORDER_DATE
ORDER BY NEW_USER DESC;


SELECT * FROM MENUITEMS
WHERE PRICE IN ( SELECT PRICE FROM MenuItems WHERE PRICE>5);

